name: UCSF NeuroAI Lab
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
url: "https://ucsf-neuroai-lab.github.io/"
description: "UCSF NeuroAI Lab - Advancing neuroscience through artificial intelligence"
